/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;

import io.apimatic.examples.*;
import io.apimatic.examples.models.*;
import io.apimatic.examples.exceptions.*;
import io.apimatic.examples.http.client.HttpClient;
import io.apimatic.examples.http.client.HttpContext;
import io.apimatic.examples.http.request.HttpRequest;
import io.apimatic.examples.http.response.HttpResponse;
import io.apimatic.examples.http.response.HttpStringResponse;
import io.apimatic.examples.http.client.APICallBack;
import io.apimatic.examples.controllers.syncwrapper.APICallBackCatcher;

public class SimpleCalculatorController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static SimpleCalculatorController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the SimpleCalculatorController class 
     */
    public static SimpleCalculatorController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new SimpleCalculatorController();
                }
            }
        }
        return instance;
    }

    /**
     * Calculates the expression using the specified operation.
     * @param    GetCalculateForCICDDemo1Input    Object containing request parameters
     * @return    Returns the Double response from the API call 
     */
    public Double getCalculateForCICDDemo1(
                final GetCalculateForCICDDemo1Input input
    ) throws Throwable {

        HttpRequest _request = _buildGetCalculateForCICDDemo1Request(input);
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetCalculateForCICDDemo1Response(_context);
    }

    /**
     * Calculates the expression using the specified operation.
     * @param    GetCalculateForCICDDemo1Input    Object containing request parameters
     * @return    Returns the void response from the API call 
     */
    public void getCalculateForCICDDemo1Async(
                final GetCalculateForCICDDemo1Input input,
                final APICallBack<Double> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetCalculateForCICDDemo1Request(input);
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            Double returnValue = _handleGetCalculateForCICDDemo1Response(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getCalculateForCICDDemo1
     */
    private HttpRequest _buildGetCalculateForCICDDemo1Request(
                final GetCalculateForCICDDemo1Input input) throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/{operation}");

        //process template parameters
        Map<String, Object> _templateParameters = new HashMap<String, Object>();
        _templateParameters.put("operation", (input.getOperation() != null) ? input.getOperation().value() : null);
        APIHelper.appendUrlWithTemplateParameters(_queryBuilder, _templateParameters);

        //process query parameters
        Map<String, Object> _queryParameters = new HashMap<String, Object>();
        _queryParameters.put("x", input.getX());
        _queryParameters.put("y", input.getY());
        APIHelper.appendUrlWithQueryParameters(_queryBuilder, _queryParameters);
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getCalculateForCICDDemo1
     * @return An object of type void
     */
    private Double _handleGetCalculateForCICDDemo1Response(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        Double _result = Double.parseDouble(_responseBody);

        return _result;
    }

}
