/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class GetCICDDemoForCalculatorInputBuilder {
    //the instance to build
    private GetCICDDemoForCalculatorInput getCICDDemoForCalculatorInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCICDDemoForCalculatorInputBuilder() {
        getCICDDemoForCalculatorInput = new GetCICDDemoForCalculatorInput();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCICDDemoForCalculatorInputBuilder operation(OperationTypeEnum operation) {
        getCICDDemoForCalculatorInput.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCICDDemoForCalculatorInputBuilder x(double x) {
        getCICDDemoForCalculatorInput.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCICDDemoForCalculatorInputBuilder y(double y) {
        getCICDDemoForCalculatorInput.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCICDDemoForCalculatorInput build() {
        return getCICDDemoForCalculatorInput;
    }
}