/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class GetCalculateForCICDDemoV2InputBuilder {
    //the instance to build
    private GetCalculateForCICDDemoV2Input getCalculateForCICDDemoV2Input;

    /**
     * Default constructor to initialize the instance
     */
    public GetCalculateForCICDDemoV2InputBuilder() {
        getCalculateForCICDDemoV2Input = new GetCalculateForCICDDemoV2Input();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCalculateForCICDDemoV2InputBuilder operation(OperationTypeEnum operation) {
        getCalculateForCICDDemoV2Input.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCalculateForCICDDemoV2InputBuilder x(double x) {
        getCalculateForCICDDemoV2Input.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCalculateForCICDDemoV2InputBuilder y(double y) {
        getCalculateForCICDDemoV2Input.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCalculateForCICDDemoV2Input build() {
        return getCalculateForCICDDemoV2Input;
    }
}