/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class GetCalculateForCICDDemo1InputBuilder {
    //the instance to build
    private GetCalculateForCICDDemo1Input getCalculateForCICDDemo1Input;

    /**
     * Default constructor to initialize the instance
     */
    public GetCalculateForCICDDemo1InputBuilder() {
        getCalculateForCICDDemo1Input = new GetCalculateForCICDDemo1Input();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCalculateForCICDDemo1InputBuilder operation(OperationTypeEnum operation) {
        getCalculateForCICDDemo1Input.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCalculateForCICDDemo1InputBuilder x(double x) {
        getCalculateForCICDDemo1Input.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCalculateForCICDDemo1InputBuilder y(double y) {
        getCalculateForCICDDemo1Input.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCalculateForCICDDemo1Input build() {
        return getCalculateForCICDDemo1Input;
    }
}