/*
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package io.apimatic.examples.models;

import java.util.*;

public class GetCICDDEMOForCalculatorInputBuilder {
    //the instance to build
    private GetCICDDEMOForCalculatorInput getCICDDEMOForCalculatorInput;

    /**
     * Default constructor to initialize the instance
     */
    public GetCICDDEMOForCalculatorInputBuilder() {
        getCICDDEMOForCalculatorInput = new GetCICDDEMOForCalculatorInput();
    }

    /**
     * The operator to apply on the variables
     */
    public GetCICDDEMOForCalculatorInputBuilder operation(OperationTypeEnum operation) {
        getCICDDEMOForCalculatorInput.setOperation(operation);
        return this;
    }

    /**
     * The LHS value
     */
    public GetCICDDEMOForCalculatorInputBuilder x(double x) {
        getCICDDEMOForCalculatorInput.setX(x);
        return this;
    }

    /**
     * The RHS value
     */
    public GetCICDDEMOForCalculatorInputBuilder y(double y) {
        getCICDDEMOForCalculatorInput.setY(y);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetCICDDEMOForCalculatorInput build() {
        return getCICDDEMOForCalculatorInput;
    }
}